In [1]:
import numpy as np

# var1=np.array((1,2,3,4,5))
# print(var1)
var2 = np.array([[1, 2, 3], [3, 4, 5]])
# print(var2)
var3=np.array([[1, 2, 3], [3, 4, 5]])
var4=np.add(var3,var2)
print(var4)


[[ 2  4  6]
 [ 6  8 10]]


In [2]:
var2 = np.array([[1, 2, 3], [3, 4, 5]])
print(var2)
print(var2.shape)
print(var2.ndim)
print(var2.size)
print(var2.dtype)
print(var2.itemsize)
print(var2.nbytes)


[[1 2 3]
 [3 4 5]]
(2, 3)
2
6
int32
4
24


In [4]:
var2 = np.array([[1, 2, 3], [3, 4, 5]])
var2 = var2.reshape(3,2)
print(var2)


[[1 2]
 [3 3]
 [4 5]]


In [12]:
x = np.linspace(1, 50, 2) # prints the numbers in range 1 to 50 with equal distance in between

print(x)
print(np.linspace(1, 50, 4, dtype = int))

[ 1. 50.]
[ 1 17 33 50]


In [23]:
y = np.array([[1,2,3],[4,5,6,],[7,8,9],[10,11,12]])
print(y[0:,1])
print('\n')
print(y[0:,1:])
print('\n')
print(y[2:,1:])

[ 2  5  8 11]


[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]


[[ 8  9]
 [11 12]]


In [26]:
y = np.array([[1,2,3],[4,52,6,],[7,8,9],[10,11,12]])
print(y.max())  # prints the maximum value in the array
print(y.min())  # prints the minimum value in the array
print(y.sum())  # prints the sum of all the elements in the array
print(y.sum(axis=0))  # prints the sum of all the elements in the array
print(y.sum(axis=1))  # prints the sum of all the elements in the array


52
1
125
[22 73 30]
[ 6 62 24 33]


In [30]:
# matrix operations

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x+y)
print('\n')
print(x-y)
print('\n')
print(x*y) # element wise multiplication
print('\n')
print(x/y)
print('\n')
print(x.dot(y)) # matrix multiplication of x and y 


[[ 6  8]
 [10 12]]


[[-4 -4]
 [-4 -4]]


[[ 5 12]
 [21 32]]


[[0.2        0.33333333]
 [0.42857143 0.5       ]]


[[19 22]
 [43 50]]


In [36]:
var2 = np.array([[1, 2, 3], [3, 4, 5]])
print(var2.sum(axis=0)) # prints the sum of all the elements in the array of each column
print(var2.sum(axis=1)) # prints the sum of all the elements in the array of each row
print(np.sqrt(var2)) # prints the square root of all the elements in the array
print(np.std(var2)) # prints the standard deviation of all the elements in the array

[4 6 8]
[ 6 12]
[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056


In [37]:
var4 = np.array([1, 2, 33, 4, 5])
print(np.exp(var4)) # prints the exponential of all the elements in the array
print(np.log(var4)) # prints the log of all the elements in the array
print(np.log10(var4)) # prints the log10 of all the elements in the array


[2.71828183e+00 7.38905610e+00 2.14643580e+14 5.45981500e+01
 1.48413159e+02]
[0.         0.69314718 3.49650756 1.38629436 1.60943791]
[0.         0.30103    1.51851394 0.60205999 0.69897   ]
