In [3]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [4]:
print("Loading Iris dataset...")
data = load_iris(return_X_y=True)
print("Iris dataset loaded.")
print("Number of samples: ", len(data[0]))
print("Number of features: ", len(data[0][0]))
print("Number of classes: ", len(np.unique(data[1])))
print("Class labels: ", np.unique(data[1]))


Loading Iris dataset...
Iris dataset loaded.
Number of samples:  150
Number of features:  4
Number of classes:  3
Class labels:  [0 1 2]


In [5]:
X = data[0]
Y = data[1]
data = np.concatenate((X,np.expand_dims(Y,axis=1)),axis=1)
np.random.shuffle(data)

In [6]:
trainData, testData = data[:int(len(data)*0.7),:], data[int(len(data)*0.7):,:] # 70% training, 30% testing
trainData_X, trainData_Y = trainData[:,:-1], trainData[:,-1]
testData_X, testData_Y = testData[:,:-1], testData[:,-1]


In [7]:
trainData_X[0], trainData_Y[0]

(array([6.5, 2.8, 4.6, 1.5]), 1.0)

In [8]:
test_sample = testData_X[0]

In [11]:
from sklearn.metrics.pairwise import euclidean_distances

In [12]:
euclidean_distances(trainData_X, np.expand_dims(test_sample,axis=0))

array([[3.92428337],
       [4.7833043 ],
       [4.23202079],
       [5.22111099],
       [4.29651021],
       [3.65786823],
       [0.65574385],
       [0.31622777],
       [3.51140997],
       [5.38237866],
       [5.43139025],
       [0.26457513],
       [0.50990195],
       [3.22645316],
       [4.51995575],
       [0.14142136],
       [4.75078941],
       [5.16623654],
       [5.67626638],
       [4.09633983],
       [4.99299509],
       [4.30697109],
       [0.9       ],
       [4.27200187],
       [3.95094925],
       [0.33166248],
       [2.81069386],
       [2.19317122],
       [0.64807407],
       [2.47386338],
       [0.55677644],
       [3.90128184],
       [2.92574777],
       [0.3       ],
       [4.16893272],
       [3.75366488],
       [3.25269119],
       [0.42426407],
       [4.29185275],
       [3.48998567],
       [4.37264222],
       [3.34065862],
       [5.75673519],
       [0.59160798],
       [4.57930126],
       [5.2516664 ],
       [6.62797103],
       [3.277

In [18]:
dist = np.concatenate(
    (euclidean_distances(trainData_X, np.expand_dims(test_sample,axis=0)),
    np.expand_dims(trainData_Y,axis=1)),
    axis=1
)

In [19]:
dist

array([[3.92428337, 1.        ],
       [4.7833043 , 2.        ],
       [4.23202079, 2.        ],
       [5.22111099, 2.        ],
       [4.29651021, 1.        ],
       [3.65786823, 2.        ],
       [0.65574385, 0.        ],
       [0.31622777, 0.        ],
       [3.51140997, 1.        ],
       [5.38237866, 2.        ],
       [5.43139025, 2.        ],
       [0.26457513, 0.        ],
       [0.50990195, 0.        ],
       [3.22645316, 1.        ],
       [4.51995575, 2.        ],
       [0.14142136, 0.        ],
       [4.75078941, 2.        ],
       [5.16623654, 2.        ],
       [5.67626638, 2.        ],
       [4.09633983, 2.        ],
       [4.99299509, 2.        ],
       [4.30697109, 2.        ],
       [0.9       , 0.        ],
       [4.27200187, 2.        ],
       [3.95094925, 1.        ],
       [0.33166248, 0.        ],
       [2.81069386, 1.        ],
       [2.19317122, 1.        ],
       [0.64807407, 0.        ],
       [2.47386338, 1.        ],
       [0.

In [20]:
dist = dist[dist[:,0].argsort()]


In [34]:
k=7
dist[:k]

array([[0.14142136, 0.        ],
       [0.26457513, 0.        ],
       [0.3       , 0.        ],
       [0.31622777, 0.        ],
       [0.31622777, 0.        ],
       [0.33166248, 0.        ],
       [0.34641016, 0.        ]])

In [35]:
unique_elements, counts_elements = np.unique(dist[:k][:,1], return_counts=True)

In [36]:
unique_elements, counts_elements

(array([0.]), array([7], dtype=int64))

In [37]:
frequency = np.concatenate(
    (np.expand_dims(unique_elements,axis=1),
    np.expand_dims(counts_elements,axis=1)),
    axis=1
)
frequency = frequency[frequency[:,1].argsort()]

In [38]:
frequency

array([[0., 7.]])