In [169]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [196]:
print("Loading Iris dataset...")
data = load_iris(return_X_y=True)
print("Iris dataset loaded.")
print("Number of samples: ", len(data[0]))
print("Number of features: ", len(data[0][0]))
print("Number of classes: ", len(np.unique(data[1])))
print("Class labels: ", np.unique(data[1]))


Loading Iris dataset...
Iris dataset loaded.
Number of samples:  150
Number of features:  4
Number of classes:  3
Class labels:  [0 1 2]


In [197]:
X = data[0]
Y = data[1]
data = np.concatenate((X,np.expand_dims(Y,axis=1)),axis=1)
np.random.shuffle(data)

In [198]:
trainData, testData = data[:int(len(data)*0.7),:], data[int(len(data)*0.7):,:] # 70% training, 30% testing
trainData_X, trainData_Y = trainData[:,:-1], trainData[:,-1]
testData_X, testData_Y = testData[:,:-1], testData[:,-1]


In [173]:
trainData_X[0], trainData_Y[0]

(array([5.9, 3.2, 4.8, 1.8]), 1.0)

In [199]:
test_sample = testData_X[0]

In [200]:
from sklearn.metrics.pairwise import euclidean_distances

In [201]:
euclidean_distances(trainData_X, np.expand_dims(test_sample,axis=0))

array([[3.57071421],
       [0.41231056],
       [1.07238053],
       [4.17851648],
       [6.04152299],
       [3.79209705],
       [3.20780299],
       [0.51961524],
       [1.48996644],
       [1.29614814],
       [4.74657771],
       [3.18433667],
       [3.15436206],
       [3.6180105 ],
       [4.07553677],
       [3.33616546],
       [4.40227214],
       [5.25452186],
       [3.13209195],
       [5.0645829 ],
       [4.6292548 ],
       [0.78102497],
       [4.62493243],
       [4.67011777],
       [0.86023253],
       [5.72538208],
       [5.10196041],
       [4.13642358],
       [0.34641016],
       [5.01298314],
       [3.63868108],
       [0.678233  ],
       [4.9010203 ],
       [4.26028168],
       [3.48137904],
       [3.36303434],
       [4.24028301],
       [3.97617907],
       [4.25323406],
       [5.12347538],
       [3.54400903],
       [3.94715087],
       [3.78813938],
       [4.61194102],
       [3.28329103],
       [1.39283883],
       [4.66154481],
       [0.948

In [202]:
dist = np.concatenate(
    (euclidean_distances(trainData_X, np.expand_dims(test_sample,axis=0)),
    np.expand_dims(trainData_Y,axis=1)),
    axis=1
)

In [178]:
dist

array([[0.86023253, 1.        ],
       [1.2328828 , 2.        ],
       [1.        , 2.        ],
       [2.62106848, 2.        ],
       [3.62629287, 0.        ],
       [2.84604989, 0.        ],
       [1.42478068, 2.        ],
       [0.6244998 , 1.        ],
       [3.09192497, 0.        ],
       [3.0757113 , 0.        ],
       [1.60312195, 2.        ],
       [1.73493516, 2.        ],
       [1.81383571, 2.        ],
       [1.42828569, 1.        ],
       [3.03973683, 0.        ],
       [0.50990195, 1.        ],
       [3.27261363, 0.        ],
       [1.1045361 , 2.        ],
       [0.72111026, 1.        ],
       [1.06770783, 2.        ],
       [0.7       , 1.        ],
       [0.64807407, 1.        ],
       [3.04959014, 0.        ],
       [3.03809151, 0.        ],
       [0.70710678, 1.        ],
       [1.88414437, 2.        ],
       [0.93273791, 1.        ],
       [0.47958315, 1.        ],
       [1.44913767, 2.        ],
       [1.99248588, 2.        ],
       [1.

In [203]:
dist = dist[dist[:,0].argsort()]


In [204]:
k=7
dist[:k]

array([[0.34641016, 0.        ],
       [0.38729833, 0.        ],
       [0.41231056, 0.        ],
       [0.51961524, 0.        ],
       [0.54772256, 0.        ],
       [0.54772256, 0.        ],
       [0.678233  , 0.        ]])

In [205]:
unique_elements, counts_elements = np.unique(dist[:k][:,1], return_counts=True)

In [206]:
unique_elements, counts_elements

(array([0.]), array([7], dtype=int64))

In [207]:
frequency = np.concatenate(
    (np.expand_dims(unique_elements,axis=1),
    np.expand_dims(counts_elements,axis=1)),
    axis=1
)
frequency = frequency[frequency[:,1].argsort()]

In [184]:
frequency

array([[1., 7.]])

In [208]:
pred_label = frequency[0,0]
pred_label

0.0

In [209]:
def knn(trainData_X, trainData_Y, test_sample, k=7):
    dist = np.concatenate(
        (euclidean_distances(trainData_X, np.expand_dims(test_sample,axis=0)),
        np.expand_dims(trainData_Y,axis=1)),
        axis=1
    )
    dist = dist[dist[:,0].argsort()]
    unique_elements, counts_elements = np.unique(dist[:k][:,1], return_counts=True)
    frequency = np.concatenate(
        (np.expand_dims(unique_elements,axis=1),
        np.expand_dims(counts_elements,axis=1)),
        axis=1
    )
    frequency = frequency[frequency[:,1].argsort()]
    pred_label = frequency[0,0]
    return pred_label

knn(trainData_X, trainData_Y, test_sample, k=7)

0.0

In [210]:
knn(trainData_X, trainData_Y, testData_X[3], k=7)

0.0

In [188]:
from sklearn.datasets import load_wine
print('Loading Wine dataset...')
data = load_wine(return_X_y=True)
print('Wine dataset loaded.')
print('Number of samples: ', len(data[0]))
print('Number of features: ', len(data[0][0]))
print('Number of classes: ', len(np.unique(data[1])))
print('Class labels: ', np.unique(data[1]))


Loading Wine dataset...
Wine dataset loaded.
Number of samples:  178
Number of features:  13
Number of classes:  3
Class labels:  [0 1 2]


In [189]:
X = data[0]
Y = data[1]
data = np.concatenate((X,np.expand_dims(Y,axis=1)),axis=1)
np.random.shuffle(data)
trainData, testData = data[:int(len(data)*0.7),:], data[int(len(data)*0.7):,:] # 70% training, 30% testing
trainData_X, trainData_Y = trainData[:,:-1], trainData[:,-1]
testData_X, testData_Y = testData[:,:-1], testData[:,-1]


In [190]:
trainData_X[0], trainData_Y[0]

(array([1.356e+01, 1.710e+00, 2.310e+00, 1.620e+01, 1.170e+02, 3.150e+00,
        3.290e+00, 3.400e-01, 2.340e+00, 6.130e+00, 9.500e-01, 3.380e+00,
        7.950e+02]),
 0.0)

In [191]:
test_sample = testData_X[0]
knn(trainData_X, trainData_Y, test_sample)


1.0

In [219]:
pred_list = [knn(trainData_X, trainData_Y, testData_X[i]) for i in range( testData_X.shape[0])]

In [220]:
print(pred_list)

[0.0, 2.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 2.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 2.0, 1.0, 2.0, 0.0, 0.0, 1.0, 1.0, 0.0, 2.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]


In [221]:
matchCount = 0
for i in range(len(testData_Y)):
    if testData_Y[i] == pred_list[i]:
        matchCount += 1
print(matchCount)

40


In [222]:
matchCount/len(testData_Y)

0.8888888888888888