In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [2]:
print("Loading Iris dataset...")
data = load_iris(return_X_y=True)
print("Iris dataset loaded.")
print("Number of samples: ", len(data[0]))
print("Number of features: ", len(data[0][0]))
print("Number of classes: ", len(np.unique(data[1])))
print("Class labels: ", np.unique(data[1]))


Loading Iris dataset...
Iris dataset loaded.
Number of samples:  150
Number of features:  4
Number of classes:  3
Class labels:  [0 1 2]


In [3]:
X = data[0]
Y = data[1]
data = np.concatenate((X,np.expand_dims(Y,axis=1)),axis=1)
np.random.shuffle(data)

In [4]:
trainData, testData = data[:int(len(data)*0.7),:], data[int(len(data)*0.7):,:] # 70% training, 30% testing
trainData_X, trainData_Y = trainData[:,:-1], trainData[:,-1]
testData_X, testData_Y = testData[:,:-1], testData[:,-1]


In [5]:
trainData_X[0], trainData_Y[0]

(array([6. , 3. , 4.8, 1.8]), 2.0)

In [6]:
test_sample = testData_X[0]

In [7]:
from sklearn.metrics.pairwise import euclidean_distances

In [8]:
euclidean_distances(trainData_X, np.expand_dims(test_sample,axis=0))

array([[3.96862697],
       [0.46904158],
       [0.58309519],
       [4.88057374],
       [3.92428337],
       [4.66047208],
       [3.61109402],
       [5.20864666],
       [0.90553851],
       [3.07408523],
       [4.21307489],
       [0.57445626],
       [4.46989933],
       [4.91731634],
       [4.14608249],
       [2.38956063],
       [3.59722115],
       [5.05272204],
       [4.93659802],
       [0.87177979],
       [4.25088226],
       [5.33760246],
       [0.68556546],
       [5.20192272],
       [4.69148164],
       [0.42426407],
       [4.2626283 ],
       [0.17320508],
       [0.24494897],
       [0.86023253],
       [5.13419906],
       [0.38729833],
       [2.88963666],
       [0.46904158],
       [3.84837628],
       [5.13711982],
       [1.161895  ],
       [4.69574275],
       [0.86023253],
       [2.75317998],
       [0.54772256],
       [0.33166248],
       [5.7210139 ],
       [3.69188299],
       [3.13368792],
       [2.94108823],
       [0.69282032],
       [3.882

In [9]:
dist = np.concatenate(
    (euclidean_distances(trainData_X, np.expand_dims(test_sample,axis=0)),
    np.expand_dims(trainData_Y,axis=1)),
    axis=1
)

In [10]:
dist

array([[3.96862697, 2.        ],
       [0.46904158, 0.        ],
       [0.58309519, 0.        ],
       [4.88057374, 2.        ],
       [3.92428337, 1.        ],
       [4.66047208, 2.        ],
       [3.61109402, 1.        ],
       [5.20864666, 2.        ],
       [0.90553851, 0.        ],
       [3.07408523, 1.        ],
       [4.21307489, 2.        ],
       [0.57445626, 0.        ],
       [4.46989933, 2.        ],
       [4.91731634, 2.        ],
       [4.14608249, 1.        ],
       [2.38956063, 1.        ],
       [3.59722115, 1.        ],
       [5.05272204, 2.        ],
       [4.93659802, 2.        ],
       [0.87177979, 0.        ],
       [4.25088226, 2.        ],
       [5.33760246, 2.        ],
       [0.68556546, 0.        ],
       [5.20192272, 2.        ],
       [4.69148164, 2.        ],
       [0.42426407, 0.        ],
       [4.2626283 , 1.        ],
       [0.17320508, 0.        ],
       [0.24494897, 0.        ],
       [0.86023253, 0.        ],
       [5.

In [11]:
dist = dist[dist[:,0].argsort()]


In [12]:
k=7
dist[:k]

array([[0.14142136, 0.        ],
       [0.17320508, 0.        ],
       [0.17320508, 0.        ],
       [0.24494897, 0.        ],
       [0.26457513, 0.        ],
       [0.3       , 0.        ],
       [0.33166248, 0.        ]])

In [13]:
unique_elements, counts_elements = np.unique(dist[:k][:,1], return_counts=True)

In [14]:
unique_elements, counts_elements

(array([0.]), array([7], dtype=int64))

In [15]:
frequency = np.concatenate(
    (np.expand_dims(unique_elements,axis=1),
    np.expand_dims(counts_elements,axis=1)),
    axis=1
)
frequency = frequency[frequency[:,1].argsort()]

In [16]:
frequency

array([[0., 7.]])

In [17]:
pred_label = frequency[0,0]
pred_label

0.0

In [27]:
def knn(trainData_X, trainData_Y, test_sample, k=7):
    dist = np.concatenate(
        (euclidean_distances(trainData_X, np.expand_dims(test_sample,axis=0)),
        np.expand_dims(trainData_Y,axis=1)),
        axis=1
    )
    dist = dist[dist[:,0].argsort()]
    unique_elements, counts_elements = np.unique(dist[:k][:,1], return_counts=True)
    frequency = np.concatenate(
        (np.expand_dims(unique_elements,axis=1),
        np.expand_dims(counts_elements,axis=1)),
        axis=1
    )
    frequency = frequency[frequency[:,1].argsort()]
    pred_label = frequency[0,0]
    return pred_label

knn(trainData_X, trainData_Y, test_sample, k=7)

2.0

In [19]:
knn(trainData_X, trainData_Y, testData_X[3], k=7)

0.0

In [20]:
from sklearn.datasets import load_wine
print('Loading Wine dataset...')
data = load_wine(return_X_y=True)
print('Wine dataset loaded.')
print('Number of samples: ', len(data[0]))
print('Number of features: ', len(data[0][0]))
print('Number of classes: ', len(np.unique(data[1])))
print('Class labels: ', np.unique(data[1]))


Loading Wine dataset...
Wine dataset loaded.
Number of samples:  178
Number of features:  13
Number of classes:  3
Class labels:  [0 1 2]


In [21]:
X = data[0]
Y = data[1]
data = np.concatenate((X,np.expand_dims(Y,axis=1)),axis=1)
np.random.shuffle(data)
trainData, testData = data[:int(len(data)*0.7),:], data[int(len(data)*0.7):,:] # 70% training, 30% testing
trainData_X, trainData_Y = trainData[:,:-1], trainData[:,-1]
testData_X, testData_Y = testData[:,:-1], testData[:,-1]


In [22]:
trainData_X[0], trainData_Y[0]

(array([1.284e+01, 2.960e+00, 2.610e+00, 2.400e+01, 1.010e+02, 2.320e+00,
        6.000e-01, 5.300e-01, 8.100e-01, 4.920e+00, 8.900e-01, 2.150e+00,
        5.900e+02]),
 2.0)

In [29]:
test_sample = testData_X[0]
knn(trainData_X, trainData_Y, test_sample)


2.0