# Kmeans Clustering definition

## importing libraries an dataset

In [5]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.metrics import euclidean_distances

data = load_iris(return_X_y=True)
X = data[0]
y = data[1]
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [6]:
n_clusters = 3

randomIndices = np.random.randint(len(y), size = (n_clusters))
print('RandomIndices: ', randomIndices)
init_centers = X[randomIndices]
print('Initial Centers: ', init_centers)


RandomIndices:  [76  8 24]
Initial Centers:  [[6.8 2.8 4.8 1.4]
 [4.4 2.9 1.4 0.2]
 [4.8 3.4 1.9 0.2]]


In [19]:
max_iter = 30
tol = 0.001

labels_ = np.full(y.shape, -1)
itr = 0
centers = init_centers
while itr < max_iter:
    print(centers)
    itr += 1

    for i in range(len(y)):
        labels_[i] = np.argmin(euclidean_distances([X[i]], centers)[0])

    next_centers = np.array([np.mean(X[labels_ == l], axis=0) for l in np.unique(labels_)])

    if(np.mean(np.abs(next_centers - centers)) < tol):
        break

    centers = next_centers

[[6.8 2.8 4.8 1.4]
 [4.4 2.9 1.4 0.2]
 [4.8 3.4 1.9 0.2]]
[[6.31458333 2.89583333 4.97395833 1.703125  ]
 [4.61538462 3.05384615 1.30769231 0.2       ]
 [5.12926829 3.43658537 1.68780488 0.33658537]]
[[6.30103093 2.88659794 4.95876289 1.69587629]
 [4.66111111 3.08888889 1.36666667 0.2       ]
 [5.18285714 3.51428571 1.66       0.33714286]]
[[6.30103093 2.88659794 4.95876289 1.69587629]
 [4.7        3.10952381 1.39047619 0.2       ]
 [5.20625    3.540625   1.671875   0.35      ]]
